### ISSUE TITLE
Opengur feedback.

### ISSUE THREAD

**Issue by Momchoto** [Kennyc1012/Opengur#195]
First of all, i REALLY like Opengur, i've used it for a while and i find it much better than the official app, but i have come across some very minor issues that i hope you can take a look at.
1. Sometimes i "run out" of posts and i can't swipe forward. To fix this, i go back to the main screen, scroll down, wait for the new posts to load and continue browsing.
2. Occasionally images in posts are loaded in very low resolution and i have to separately open them to view them properly.
_Nitpicking..._
3. The "collapse" button in the comment section is way too small and pretty hard to press, also when i collapse the box around the button gets a little cut off.

**Comment by Kennyc1012** [comment]
1. This is intended. If there are too many items to swipe between, the app will crash.

2. This happens when the image is very large (pixel wise). Android has a limitation of how large it can display an image (2048pxX2048px). Anything larger needs to be downscaled which is why the larger images appear blurry. When you open them separately, only the area you are viewing is decoded, resulting in a better quality image.

3. I know. I've experimented with different sizes but found that anything larger messes up the flow of the comments. I need to find a better solution to this.
